"""Stage 07 — Generate the full static analysis site.

Reads cluster_xy_table__<CLUSTER_TABLES[0]>.csv + its cluster_labels file and writes
the entire browsable site into docs/ (the GitHub Pages root):

    docs/
    ├── index.html                       (landing — generated since Entry 008)
    ├── site.css                         (site-wide stylesheet, single source)
    ├── interactive_clusters__*.html     (interactive maps — already exist)
    ├── cluster_evidence.html            (master index of clusters)
    ├── methods.html                     (how every on-page label is computed)
    ├── cluster_NN.html                  (one page per cluster)
    └── characters/<char_id>.html        (one page per character)

A scholar who clones the repo and runs the pipeline through stage 07 gets
the full site regenerated. The cluster pages list every character with
algorithmically-detected important excerpts; each character links to a deep-
dive page with the full speech text plus all metadata.

Run after stages 04 and 05:
    python code/07_generate_site.py
"""

from __future__ import annotations
import html
import re
import pandas as pd
from pathlib import Path
from collections import Counter

import config


# -------------------------------------------------------------------
# Tuning knobs
# -------------------------------------------------------------------
N_EXCERPTS_PER_CHAR_CLUSTER_PAGE = 2   # excerpts shown on the cluster page
N_EXCERPTS_PER_CHAR_DETAIL       = 5   # excerpts shown on the character page
EXCERPT_HALF_WINDOW              = 160 # characters either side of a keyword hit
TOP_CHARS_WITH_EXCERPTS_ON_CLUSTER = 40 # cap for the big residue clusters


# -------------------------------------------------------------------
# Site-wide stylesheet — single source of truth, written to docs/site.css
# by main() so every page (incl. 6,466 character pages) shares one file
# and future redesigns touch one artifact (Entry 008, 2026-07-10:
# "clean modern academic" system — type scale, spacing, unified badge
# palette, sticky masthead + roster header).
# -------------------------------------------------------------------
SITE_CSS = """
/* Early Modern Drama — Character Clustering · site.css
   Generated by code/07_generate_site.py — edit there, not here. */
:root {
  --ink: #1b1b22; --muted: #5f5f6b; --faint: #8b8b95;
  --accent: #5a4a8a; --accent-ink: #45376f; --accent-soft: #efecf7;
  --bg: #fbfbf8; --card: #ffffff; --rule: #e6e6df; --soft: #f3f3ec;
  --warm: #f8f4e8;
  --b-proto-bg: #e9e3f6; --b-proto-fg: #4a3a7a;
  --b-typ-bg:  #e3ebf3;  --b-typ-fg:  #3c5570;
  --b-fam-bg:  #ececec;  --b-fam-fg:  #55555f;
  --b-time-bg: #f5eecb;  --b-time-fg: #7a6a2e;
  --highlight: #fff3a8;
  --maxw: 1060px; --mast-h: 47px;
}
* { box-sizing: border-box; }
html { scroll-padding-top: calc(var(--mast-h) + 12px); }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue",
       Helvetica, Arial, sans-serif;
       color: var(--ink); background: var(--bg); margin: 0; padding: 0;
       line-height: 1.6; font-size: 16px;
       -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; }

/* ---- masthead ------------------------------------------------------ */
.masthead { position: sticky; top: 0; z-index: 60; height: var(--mast-h);
            background: rgba(255,255,255,.92); backdrop-filter: blur(8px);
            -webkit-backdrop-filter: blur(8px); border-bottom: 1px solid var(--rule); }
.masthead .in { max-width: var(--maxw); margin: 0 auto; height: 100%;
                padding: 0 28px; display: flex; align-items: center; gap: 20px; }
.masthead .brand { font-weight: 700; font-size: .95rem; letter-spacing: -.01em;
                   color: var(--ink); text-decoration: none; white-space: nowrap; }
.masthead .brand span { color: var(--faint); font-weight: 500; }
.masthead nav { margin-left: auto; display: flex; gap: 4px; font-size: .88rem; }
.masthead nav a { color: var(--muted); text-decoration: none; padding: 4px 10px;
                  border-radius: 6px; }
.masthead nav a:hover { color: var(--accent-ink); background: var(--accent-soft); }
.masthead nav a.active { color: var(--accent-ink); background: var(--accent-soft);
                         font-weight: 600; }

/* ---- layout & type ------------------------------------------------- */
.wrap { max-width: var(--maxw); margin: 0 auto; padding: 34px 28px 96px; }
nav.crumbs { font-size: .82rem; color: var(--faint); margin: 0 0 1.6em; }
nav.crumbs a { color: var(--muted); text-decoration: none; }
nav.crumbs a:hover { color: var(--accent); text-decoration: underline; }
h1 { font-size: 1.85rem; font-weight: 750; letter-spacing: -.022em;
     line-height: 1.2; margin: 0 0 .3em; }
h2 { font-size: 1.02rem; font-weight: 700; letter-spacing: .005em;
     margin: 3em 0 .8em; padding-bottom: .45em; border-bottom: 1px solid var(--rule);
     display: flex; align-items: baseline; gap: 8px; }
h2::before { content: ""; width: 22px; height: 4px; border-radius: 2px;
             background: var(--accent); align-self: center; flex: none; opacity: .85; }
h3 { font-size: .95rem; font-weight: 650; margin: 1.6em 0 .4em; }
p { max-width: 76ch; }
.lede { color: var(--muted); margin: 0 0 1.3em; max-width: 78ch; }
.lede.sub { font-size: .92rem; }
a { color: var(--accent); }
code { background: var(--soft); border-radius: 4px; padding: 1px 5px; font-size: .88em; }

/* ---- fact strip ---------------------------------------------------- */
.facts { display: flex; flex-wrap: wrap; gap: 6px 34px; margin: 1.2em 0 1.5em; }
.facts .f { min-width: 0; }
.facts .f b { display: block; font-size: 1.22rem; font-weight: 700;
              letter-spacing: -.01em; line-height: 1.25; font-variant-numeric: tabular-nums; }
.facts .f i { font-style: normal; display: block; font-size: .78rem; color: var(--muted);
              letter-spacing: .04em; text-transform: uppercase; }
.kvp { display: flex; flex-wrap: wrap; gap: 8px 18px; font-size: .92rem;
       color: var(--muted); margin-bottom: .8em; }
.kvp b { color: var(--ink); font-weight: 650; }

/* ---- notes & banners ----------------------------------------------- */
.banner { background: var(--accent-soft); border-left: 3px solid var(--accent);
          border-radius: 0 8px 8px 0; padding: 10px 16px; font-size: .88rem;
          line-height: 1.55; margin: 0 0 1.6em; color: #3f3f49; max-width: none; }
.banner b { color: var(--ink); }
.kw-caveat { color: var(--faint); font-size: .82rem; margin: -.8em 0 1.4em; max-width: 78ch; }
.curated { background: #fbf7ee; border: 1px solid #eadfc8; border-radius: 10px;
           padding: 12px 18px; margin: 0 0 1.4em; font-size: .93rem; }
.curated .clabel { font-weight: 650; font-size: .72rem; letter-spacing: .06em;
                   color: #7a6a2e; text-transform: uppercase; margin-right: .5em; }

/* ---- badges & chips (one system) ----------------------------------- */
.badge, .chip {
  display: inline-block; font-size: .64rem; font-weight: 700; letter-spacing: .05em;
  text-transform: uppercase; border-radius: 999px; padding: 2px 8px;
  margin-left: 6px; vertical-align: 2px;
  background: var(--b-fam-bg); color: var(--b-fam-fg); white-space: nowrap; }
.badge-proto, .chip-prototype { background: var(--b-proto-bg); color: var(--b-proto-fg); }
.chip-typical { background: var(--b-typ-bg); color: var(--b-typ-fg); }
.badge-time { background: var(--b-time-bg); color: var(--b-time-fg); }

/* ---- cards --------------------------------------------------------- */
.idx-card { display: block; background: var(--card); border: 1px solid var(--rule);
            border-radius: 10px; padding: 15px 20px; margin: 10px 0;
            text-decoration: none; color: inherit;
            transition: border-color .12s, box-shadow .12s; }
.idx-card:hover { border-color: #c9c0e2; box-shadow: 0 2px 10px rgba(90,74,138,.08); }
.idx-card h3 { margin: 0 0 .25em; color: var(--accent-ink); font-size: 1rem; }
.idx-card p { margin: 0; color: var(--muted); font-size: .88rem; line-height: 1.55; }
.idx-card small { color: var(--faint); }
.landmarks { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
             gap: 10px; margin: .6em 0 1em; }
.lm-card { background: var(--card); border: 1px solid var(--rule); border-radius: 10px;
           padding: 11px 15px; font-size: .9rem; }
.lm-card .who { font-weight: 650; display: flex; align-items: baseline; gap: 4px;
                justify-content: space-between; flex-wrap: wrap; }
.lm-card .who a { color: var(--accent-ink); text-decoration: none; }
.lm-card .who a:hover { text-decoration: underline; }
.lm-card .whence { color: var(--muted); font-size: .84rem; margin-top: 2px; }
h2.fam { margin-top: 3.2em; }
.fam-desc { color: var(--muted); font-size: .9rem; margin: -.2em 0 .6em; }

/* ---- tables -------------------------------------------------------- */
table { border-collapse: collapse; width: 100%; font-size: .89rem; margin-top: .6em; }
th, td { padding: 7px 10px; text-align: left; border-bottom: 1px solid var(--rule);
         vertical-align: top; }
thead th { background: var(--soft); font-weight: 650; font-size: .8rem;
           letter-spacing: .03em; text-transform: uppercase; color: var(--muted); }
table.sortable thead th { position: sticky; top: var(--mast-h); z-index: 10; }
td.num { text-align: right; font-variant-numeric: tabular-nums; }
td a { color: var(--accent-ink); text-decoration: none; }
td a:hover { text-decoration: underline; }
tbody tr:hover td { background: #f6f6ef; }
tr.formative td { background: var(--warm); }
tr.formative:hover td { background: #f3edda; }
tr.formative td:first-child { box-shadow: inset 3px 0 0 #cfc3e8; }
th.sortable { cursor: pointer; user-select: none; }
th.sortable:hover { background: #eaeae1; }
th.sortable::after { content: " ↕"; color: var(--faint); font-size: .85em; }

/* ---- bars, strips, sparks ------------------------------------------ */
.bar { display: flex; align-items: center; gap: 8px; font-size: .85rem;
       color: var(--muted); margin: 1px 0; }
.bar .label { width: 5.5em; text-align: right; }
.bar .fill { background: #c9bfe0; height: 11px; border-radius: 4px; min-width: 1px; }
.bar .count { width: 3em; }
.tag { display: inline-block; background: var(--soft); border-radius: 999px;
       padding: 2px 10px; font-size: .84rem; margin: 0 4px 5px 0; }
.tag .n { color: var(--faint); margin-left: 4px; font-size: .92em; }
.tstrip { display: flex; align-items: flex-end; gap: 2px; height: 60px; margin: .7em 0 .2em; }
.tslot { position: relative; width: 9px; height: 56px; }
.tslot .c1 { position: absolute; bottom: 0; left: 0; width: 4px; background: #ddddd3; border-radius: 1px; }
.tslot .c2 { position: absolute; bottom: 0; right: 0; width: 4px; background: var(--accent);
             border-radius: 1px; opacity: .85; }
.taxis { font-size: .76rem; color: var(--faint); margin-bottom: .6em; max-width: 78ch; }
.sig-group { margin: .3em 0 .55em; }
.sig-group .glabel { display: inline-block; min-width: 7.5em; color: var(--muted);
                     font-size: .8rem; letter-spacing: .04em; text-transform: uppercase;
                     vertical-align: top; padding-top: 3px; }
.spark { display: inline-flex; align-items: flex-end; gap: 1px; height: 14px; margin-left: 8px; }
.spark i { display: inline-block; width: 3px; background: #c9bfe0; }

/* ---- excerpts & character blocks ----------------------------------- */
.character-block { background: var(--card); border: 1px solid var(--rule);
                   border-radius: 10px; padding: 14px 18px; margin: 14px 0; }
.character-block .ch-head { display: flex; justify-content: space-between;
                            flex-wrap: wrap; gap: 6px 10px; }
.character-block .ch-head .name { font-weight: 650; font-size: 1rem; }
.character-block .ch-head .name a { color: var(--accent-ink); text-decoration: none; }
.character-block .ch-head .name a:hover { text-decoration: underline; }
.character-block .ch-head .meta { color: var(--faint); font-size: .85rem; text-align: right; }
.excerpt { background: var(--soft); border-left: 3px solid var(--accent);
           border-radius: 0 6px 6px 0; padding: 9px 14px; margin: 8px 0;
           font-family: Georgia, "Iowan Old Style", "Times New Roman", serif;
           font-size: .97rem; line-height: 1.55; }
mark { background: var(--highlight); padding: 0 2px; border-radius: 2px; }
.plot { background: var(--card); border: 1px solid var(--rule); border-radius: 8px;
        padding: 12px 16px; margin: 10px 0; }
.plot .title { font-weight: 650; margin-bottom: .2em; }
.plot .meta { color: var(--faint); font-size: .85rem; margin-bottom: .5em; }
.plot .body { font-size: .93rem; }
.full-speech { background: var(--card); border: 1px solid var(--rule); border-radius: 10px;
               padding: 18px 22px; font-family: Georgia, "Iowan Old Style",
               "Times New Roman", serif; font-size: 1rem; line-height: 1.68;
               max-height: 640px; overflow-y: auto; }

/* ---- disclosure ---------------------------------------------------- */
details { margin: 1.1em 0; border: 1px solid var(--rule); border-radius: 10px;
          background: var(--card); padding: 0 18px; }
details > summary { cursor: pointer; font-weight: 650; font-size: .95rem;
                    padding: 12px 0; color: var(--ink); list-style: none; }
details > summary::before { content: "▸"; color: var(--accent); margin-right: 8px;
                            display: inline-block; transition: transform .12s; }
details[open] > summary::before { transform: rotate(90deg); }
details[open] { padding-bottom: 14px; }
details > summary::-webkit-details-marker { display: none; }

/* ---- landing ------------------------------------------------------- */
.hero { padding: 30px 0 6px; }
.hero h1 { font-size: 2.15rem; max-width: 28ch; }
.hero .lede { font-size: 1.06rem; max-width: 62ch; margin-bottom: 1.8em; }
.entries { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
           gap: 14px; margin: 1.4em 0 .6em; }
.entry { display: block; background: var(--card); border: 1px solid var(--rule);
         border-radius: 12px; padding: 18px 20px 16px; text-decoration: none;
         color: inherit; transition: border-color .12s, box-shadow .12s; }
.entry:hover { border-color: #c9c0e2; box-shadow: 0 3px 14px rgba(90,74,138,.1); }
.entry h3 { margin: 0 0 .3em; font-size: 1.02rem; color: var(--accent-ink); }
.entry p { margin: 0 0 .8em; color: var(--muted); font-size: .88rem; line-height: 1.5; }
.entry .go { font-size: .85rem; color: var(--accent); font-weight: 600; }
.methods h2 { margin-top: 2.6em; }
.methods p b { color: var(--ink); }

/* ---- footer -------------------------------------------------------- */
.footer { color: var(--faint); font-size: .84rem; margin-top: 4em;
          border-top: 1px solid var(--rule); padding-top: 1.4em; max-width: none; }
.footer a { color: var(--muted); }

/* ---- small screens ------------------------------------------------- */
@media (max-width: 760px) {
  .wrap { padding: 24px 16px 72px; }
  .masthead .in { padding: 0 16px; gap: 10px; }
  .masthead .brand span { display: none; }
  .facts { gap: 6px 22px; }
  table.sortable { display: block; overflow-x: auto; }
  .hero h1 { font-size: 1.7rem; }
}
"""

# Authors whose plays general readers are most likely to know — used to pick
# "familiar landmarks" per cluster (never affects the clustering itself).
FAMILIAR_AUTHORS = {"Shakespeare", "Jonson", "Marlowe", "Middleton", "Fletcher",
                    "Webster", "Kyd", "Ford", "Massinger", "Beaumont", "Dekker",
                    "Chapman", "Heywood", "Marston", "Shirley", "Lyly", "Greene"}

REPO_URL = "https://github.com/hkim1596/early-modern-drama-character-clustering"


def page_head(title: str, root: str = "") -> str:
    """Shared <head> contents; every page links the one docs/site.css."""
    return (f'<meta charset="utf-8">\n'
            f'<meta name="viewport" content="width=device-width,initial-scale=1">\n'
            f'<title>{esc(title)} · Character Clustering</title>\n'
            f'<link rel="stylesheet" href="{root}site.css">')


def masthead(root: str = "", active: str = "") -> str:
    """Sticky site header with primary navigation (Entry 008)."""
    def cls(k):
        return ' class="active"' if k == active else ""
    return (f'<header class="masthead"><div class="in">'
            f'<a class="brand" href="{root}index.html">Early Modern Drama'
            f' <span>· Character Archetypes</span></a>'
            f'<nav>'
            f'<a{cls("map")} href="{root}interactive_clusters__archetype.html">Map</a>'
            f'<a{cls("clusters")} href="{root}cluster_evidence.html">Clusters</a>'
            f'<a{cls("methods")} href="{root}methods.html">Methods</a>'
            f'<a href="{REPO_URL}">GitHub</a>'
            f'</nav></div></header>')


def load_cluster_meta() -> dict:
    """Curated names/families from data/cluster_names__<name>.json (optional)."""
    path = config.DATA_DIR / f"cluster_names__{config.CLUSTER_TABLES[0]}.json"
    if not path.exists():
        return {}
    import json as _json
    with open(path, encoding="utf-8") as f:
        return {int(k): v for k, v in _json.load(f).get("clusters", {}).items()}


def load_cluster_meta_top() -> dict:
    """Whole cluster_names JSON (top-level optional keys: families, attested_types)."""
    path = config.DATA_DIR / f"cluster_names__{config.CLUSTER_TABLES[0]}.json"
    if not path.exists():
        return {}
    import json as _json
    with open(path, encoding="utf-8") as f:
        return _json.load(f)


def load_cluster_summary() -> dict:
    """Run parameters + audited stats from data/cluster_summary__<name>.json."""
    path = config.DATA_DIR / f"cluster_summary__{config.CLUSTER_TABLES[0]}.json"
    if not path.exists():
        return {}
    import json as _json
    with open(path, encoding="utf-8") as f:
        return _json.load(f)


# -------------------------------------------------------------------
# Tier-1 evidence-page update (2026-07-10, PROVENANCE_LOG Entry 006)
# -------------------------------------------------------------------
# Partition identity shown in the reading-guidance banner. Update when the
# partition changes (ids reshuffle on every stage-04 re-run).
PARTITION_NOTE = "2026-07-07 NOS-verified run"
# Seed-to-seed stability is not recorded in cluster_summary__*.json; the value
# is from Clustering_Results_Report_2026-07-08 (5 refits: ARI 0.292,
# range 0.260–0.345). Re-measure and update after any re-cluster.
SEED_ARI_TEXT = "seed-to-seed ARI 0.29 (0.26–0.35 over 5 refits; report 2026-07-08)"

# Historical-profile badge rules (documented in PROVENANCE_LOG Entry 006):
# a cluster is badged from its DATED members only, and only if ≥20 are dated.
#   early-rooted : pre-1590 share ≥ 1.4 × the corpus pre-1590 share
#   late register: post-1625 share ≥ 1.15 × corpus AND median year > corpus median
# On the 2026-07-07 partition these rules reproduce the report's early
# (cl2/15/22/11) and late (cl20/19/4) lists.
BADGE_EARLY_LIFT = 1.40
BADGE_LATE_LIFT  = 1.15
MIN_DATED_FOR_BADGES = 20

# Signature panels: minimum members carrying a facet before a lift is shown,
# and the minimum lift that counts as a signature.
SIG_MIN_N = {"author": 4, "genre": 5, "company": 5, "theater": 5, "play_type": 5}
SIG_MIN_LIFT = 1.2
SIG_TOP = 5

# ---------------------------------------------------------------------
# Emergence + prototype rules (2026-07-10, PROVENANCE_LOG Entry 007).
# Replaces the old "early = first 5 dated roster rows" badge, which ignored
# typicality (measured: those five sat at the 35th typicality percentile on
# average; in 16/25 clusters at most one reached the cluster median).
#
# Year basis for everything genealogical: PERFORMANCE-FIRST — the parsed
# date_first_performance where available, else the catalogued year
# (year_analysis). Entry-005 display fill years (late-skewed parent-volume
# print years) are excluded from the emergence computation, but do serve as
# the last-resort roster display year (year_roster) so no row is undated.
#
#   established year = the year the first EMERGE_Q share (a tenth) of the
#                      cluster's dated members has appeared ("established by")
#   formative era    = members dated up to and including that year
#   prototype        = formative-era member with typicality >= the cluster
#                      median, top PROTO_TOP_N by typicality
# Simple sustained-window rules ("first decade with >=3 members, recurring")
# were tested and rejected: they collapse to the corpus onset (1544-1584) for
# nearly every cluster — they track corpus survival, not the cluster's own
# take-off.
# ---------------------------------------------------------------------
EMERGE_MIN_DATED = 20     # below this, no emergence line and no prototype badges
EMERGE_Q         = 0.10   # "established by" = first tenth of dated members
PROTO_TYP_GATE_Q = 0.50   # typicality gate: cluster median centroid_sim
PROTO_TOP_N      = 5
YEAR_SANE_RANGE  = (1400, 1700)   # parsed performance years outside → treated missing


def render_reading_banner(summary: dict) -> str:
    """RQ1/RQ30 framing + partition identity (proposal item 1.1)."""
    k    = summary.get("k", "?")
    n    = summary.get("n_clustered")
    seed = summary.get("random_state", "?")
    sil  = summary.get("silhouette_cosine_full")
    n_s  = f"{n:,}" if isinstance(n, int) else "?"
    sil_s = f"{sil:.3f}" if isinstance(sil, (int, float)) else "?"
    return (f'<div class="banner"><b>How to read these pages.</b> '
            f'Partition: {PARTITION_NOTE} (k={k}, seed {seed}, {n_s} characters). '
            f'Character-space is a <b>continuum with dense prototype regions</b>, not a set of '
            f'discrete boxes (silhouette {sil_s}; {SEED_ARI_TEXT}): read each cluster as a '
            f'density peak, membership as graded, and low-typicality members as blends of '
            f'several regions. Cluster ids are not stable across re-clustering runs. '
            f'How every label and number here is computed: '
            f'<a href="methods.html">Methods &amp; labels</a>.</div>')


def _analysis_years(frame: pd.DataFrame) -> pd.Series:
    """Year series used for the historical profile: the performance year as
    recorded in the master table (numeric + 4-digit extraction), WITHOUT the
    Entry-005 display-layer fill years (parent-volume print years, late-
    skewed). This reproduces the report's dated base exactly (n=6,040,
    median 1611, pre-1590 8.6%, post-1625 31.8% on the 2026-07-07 partition);
    the roster/landmark 'Year' columns keep the display year."""
    col = "year_analysis" if "year_analysis" in frame.columns else "year"
    return frame[col].dropna().astype(int)


def corpus_context(df: pd.DataFrame) -> dict:
    """Corpus-wide baselines (clustered characters only) shared by all pages:
    5-year-bin date shares, median/pre-1590/post-1625, and facet base rates."""
    from utils import split_facets
    cl = df[df.cluster >= 0]
    dated = _analysis_years(cl)
    bin_of = lambda y: int(y) // 5 * 5
    bins = sorted({bin_of(y) for y in dated})
    bin_counts = Counter(bin_of(y) for y in dated)
    nd = len(dated)

    facet_base: dict[str, Counter] = {}
    facet_known: dict[str, int] = {}
    for col, kind in [("author", "author"), ("genre", None), ("company", None),
                      ("theater", None), ("play_type", None)]:
        c: Counter = Counter()
        known = 0
        if col in cl.columns:
            for v in cl[col]:
                f = set(split_facets(v, kind=kind))
                if f:
                    known += 1
                    c.update(f)
        facet_base[col] = c
        facet_known[col] = known

    return {
        "n": len(cl),
        "dated_n": nd,
        "median": int(dated.median()) if nd else None,
        "pre_share": float((dated < 1590).mean()) if nd else 0.0,
        "post_share": float((dated > 1625).mean()) if nd else 0.0,
        "bins": bins,
        "bin_share": {b: bin_counts[b] / nd for b in bins} if nd else {},
        "facet_base": facet_base,
        "facet_known": facet_known,
    }


def render_temporal_strip(sub: pd.DataFrame, ctx: dict) -> tuple[str, list[str]]:
    """Historical profile (proposal item 1.3): paired 5-year-bin share bars
    (cluster vs corpus), headline stats, and early/late badges per the rules
    above. Returns (html, badge_names)."""
    dated = _analysis_years(sub)
    nd, n = len(dated), len(sub)
    if nd < 10:
        return (f"<p class='lede' style='font-size:.92rem'><em>Only {nd} of {n} members "
                f"are dated — temporal profile omitted.</em></p>", [])

    med = int(dated.median())
    pre, post = float((dated < 1590).mean()), float((dated > 1625).mean())
    cmed, cpre, cpost = ctx["median"], ctx["pre_share"], ctx["post_share"]
    pre_lift  = pre / cpre if cpre else float("nan")
    post_lift = post / cpost if cpost else float("nan")

    badges = []
    if nd >= MIN_DATED_FOR_BADGES and pre_lift >= BADGE_EARLY_LIFT:
        badges.append("early-rooted")
    if nd >= MIN_DATED_FOR_BADGES and post_lift >= BADGE_LATE_LIFT and med > cmed:
        badges.append("late register")

    bin_of = lambda y: int(y) // 5 * 5
    counts = Counter(bin_of(y) for y in dated)
    shares = {b: counts.get(b, 0) / nd for b in ctx["bins"]}
    max_share = max(max(shares.values(), default=0.0),
                    max(ctx["bin_share"].values(), default=0.0)) or 1.0
    slots = []
    for b in ctx["bins"]:
        cs, ks = ctx["bin_share"].get(b, 0.0), shares.get(b, 0.0)
        h1 = max(1, round(50 * cs / max_share))
        h2 = max(1 if counts.get(b, 0) else 0, round(50 * ks / max_share))
        lift = (ks / cs) if cs else float("nan")
        tip = (f"{b}–{b+4}: {counts.get(b, 0)} member(s), {ks:.1%} of cluster "
               f"(corpus {cs:.1%}" + (f", ×{lift:.1f}" if cs else "") + ")")
        slots.append(f'<div class="tslot" title="{esc(tip)}">'
                     f'<div class="c1" style="height:{h1}px"></div>'
                     + (f'<div class="c2" style="height:{h2}px"></div>' if h2 else "")
                     + '</div>')
    axis = (f'<div class="taxis">{ctx["bins"][0]}–{ctx["bins"][-1] + 4} in 5-year bins · '
            f'<span style="color:var(--accent)">▮</span> this cluster vs '
            f'<span style="color:#b7b7ac">▮</span> corpus (share of dated members; hover for '
            f'numbers). Catalogued-year basis (largely print years), matching the published '
            f'report; Entry-005 display fill years excluded. The roster below uses '
            f'performance-first dating instead, so its years can sit earlier than this strip '
            f'(<a href="methods.html">why two bases</a>).</div>')

    stats = (f'<div class="kvp">'
             f'<span><b>{nd}</b> dated of {n}</span>'
             f'<span>median <b>{med}</b> (corpus {cmed})</span>'
             f'<span>pre-1590 <b>{pre:.0%}</b> (corpus {cpre:.0%}, ×{pre_lift:.1f})</span>'
             f'<span>post-1625 <b>{post:.0%}</b> (corpus {cpost:.0%}, ×{post_lift:.1f})</span>'
             f'</div>')
    return (stats + f'<div class="tstrip">{"".join(slots)}</div>' + axis, badges)


def render_signature_panel(sub: pd.DataFrame, ctx: dict) -> str:
    """Signatures as lift vs the clustered corpus (proposal item 1.4):
    share-of-members-carrying-facet in cluster ÷ same share in corpus."""
    from utils import split_facets
    n_sub, n_corpus = len(sub), ctx["n"]
    groups = [("Authors", "author", "author"), ("Genres", "genre", None),
              ("Companies", "company", None), ("Theaters", "theater", None),
              ("Play types", "play_type", None)]
    out = []
    for label, col, kind in groups:
        if col not in sub.columns:
            continue
        c: Counter = Counter()
        known = 0
        for v in sub[col]:
            f = set(split_facets(v, kind=kind))
            if f:
                known += 1
                c.update(f)
        base = ctx["facet_base"][col]
        rows = []
        for facet, cn in c.items():
            if cn < SIG_MIN_N[col]:
                continue
            bn = base.get(facet, 0)
            if not bn:
                continue
            lift = (cn / n_sub) / (bn / n_corpus)
            if lift >= SIG_MIN_LIFT:
                rows.append((lift, cn, facet))
        rows.sort(reverse=True)
        if rows:
            tags = "".join(f'<span class="tag">{esc(f)} ×{l:.1f}<span class="n">n={cn}</span></span>'
                           for l, cn, f in rows[:SIG_TOP])
        else:
            tags = '<span class="tag" style="color:var(--muted)">no strong signature</span>'
        cov = ""
        if known / n_sub < 0.9:
            cov = (f' <span style="color:var(--muted); font-size:.82rem">'
                   f'(known for {known / n_sub:.0%} of members)</span>')
        out.append(f'<div class="sig-group"><span class="glabel">{label}</span> {tags}{cov}</div>')
    note = ('<p class="lede" style="font-size:.88rem">×lift = share of this cluster\'s members '
            f'with the facet ÷ the same share over all {n_corpus:,} clustered characters '
            f'(only facets carried by ≥{SIG_MIN_N["genre"]} members, lift ≥ {SIG_MIN_LIFT}, top {SIG_TOP} shown; '
            f'authors ≥{SIG_MIN_N["author"]}). Raw counts are in the collapsed list below.</p>')
    return note + "".join(out)


def render_curated_block(entry: dict) -> str:
    """Curated interpretation (proposal item 1.5): optional per-cluster fields
    historical_types / note / criticism in cluster_names__<name>.json."""
    if not entry:
        return ""
    types = entry.get("historical_types") or []
    note  = (entry.get("note") or "").strip()
    crit  = (entry.get("criticism") or "").strip()
    if not (types or note or crit):
        return ""
    parts = []
    if types:
        tags = "".join(f'<span class="tag">{esc(t)}</span>' for t in types)
        parts.append(f'<div><span class="clabel">Historical identifications</span> {tags}</div>')
    if note:
        parts.append(f'<div style="margin-top:.35em">{esc(note)}</div>')
    if crit:
        parts.append(f'<div style="margin-top:.35em"><span class="clabel">Criticism hooks</span> '
                     f'{esc(crit)}</div>')
    return f'<div class="curated">{"".join(parts)}</div>'


# render_name_badge removed 2026-07-10 (Entry 010, at Heejin's direction):
# no "proposed" marker renders anywhere. Name provenance lives only in
# data/cluster_names__<name>.json (name_provenance) and the PROVENANCE_LOG
# (Entries 004/009). Future assistant-proposed names, if any, are recorded
# the same way — never surfaced as on-page badges.


def render_decade_spark(sub: pd.DataFrame) -> str:
    """Tiny inline decade sparkline for index cards (proposal item 1.7).
    Performance-first decades (Entry 007) when year_roster is available."""
    dec = (decade_series(sub["year_roster"]) if "year_roster" in sub.columns
           else sub["Date_Decade"])
    counts = dec.dropna().astype(str).value_counts()
    counts = counts[~counts.index.str.lower().str.startswith("unknown")]
    if counts.empty:
        return ""
    decades = sort_decades(list(counts.index))
    mx = counts.max()
    bars = "".join(f'<i style="height:{max(2, round(13 * counts[d] / mx))}px"></i>'
                   for d in decades)
    return f'<span class="spark" title="decades {esc(decades[0])}–{esc(decades[-1])}">{bars}</span>'


def decade_series(years: pd.Series) -> pd.Series:
    """'1590s'-style decade labels from a numeric year series (NaN-safe)."""
    dec = (pd.to_numeric(years, errors="coerce") // 10 * 10)
    return dec.map(lambda d: f"{int(d)}s" if pd.notna(d) else float("nan"))


def compute_emergence(sub: pd.DataFrame) -> dict:
    """Emergence + prototype candidates (PROVENANCE_LOG Entry 007).

    Operates on `year_gen` (performance-first: date_first_performance where
    parseable, else the catalogued year; Entry-005 display fills excluded) and
    `centroid_sim`. Returns {} when fewer than EMERGE_MIN_DATED members are
    dated. Index values refer to `sub`'s index (call AFTER any reset_index).
    """
    if "year_gen" not in sub.columns:
        return {}
    d = sub[sub["year_gen"].notna()]
    n = len(d)
    if n < EMERGE_MIN_DATED:
        return {}
    ys = d["year_gen"].astype(int).sort_values()
    k = max(1, int(-(-EMERGE_Q * n // 1)))          # ceil(EMERGE_Q * n)
    established = int(ys.iloc[k - 1])
    first_year = int(ys.iloc[0])
    # name the first recorded member (highest typicality among the first year's)
    firsts = d[d["year_gen"] == first_year]
    first_row = firsts.loc[firsts["centroid_sim"].idxmax()] \
        if firsts["centroid_sim"].notna().any() else firsts.iloc[0]
    gate = float(sub["centroid_sim"].median())
    formative = d[d["year_gen"] <= established]
    proto = formative[formative["centroid_sim"] >= gate] \
        .nlargest(PROTO_TOP_N, "centroid_sim")
    n_perf = int(sub["year_perf"].notna().sum()) if "year_perf" in sub.columns else 0
    return {
        "n_dated": n, "n_perf": n_perf,
        "first_year": first_year,
        "first_name": str(first_row.get("display_name") or "?"),
        "first_play": str(first_row.get("title") or ""),
        "established": established,
        "gate": gate,
        "formative_idx": set(formative.index),
        "n_formative": len(formative),
        "n_pass_gate": int((formative["centroid_sim"] >= gate).sum()),
        "proto_idx": list(proto.index),
    }


SORT_JS = """
<script>
document.querySelectorAll("table.sortable th").forEach(function (th, ci) {
  th.classList.add("sortable");
  th.addEventListener("click", function () {
    var tb = th.closest("table").querySelector("tbody");
    var rows = Array.from(tb.querySelectorAll("tr"));
    var dir = th.dataset.dir === "asc" ? -1 : 1;
    th.dataset.dir = dir === 1 ? "asc" : "desc";
    rows.sort(function (a, b) {
      var x = a.children[ci].dataset.v ?? a.children[ci].textContent.trim();
      var y = b.children[ci].dataset.v ?? b.children[ci].textContent.trim();
      var nx = parseFloat(x), ny = parseFloat(y);
      if (!isNaN(nx) && !isNaN(ny)) return (nx - ny) * dir;
      if (x === "" && y !== "") return 1;
      if (y === "" && x !== "") return -1;
      return x.localeCompare(y) * dir;
    });
    rows.forEach(function (r) { tb.appendChild(r); });
  });
});
</script>
"""


# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------
def esc(x) -> str:
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return ""
    return html.escape(str(x), quote=True)


def slugify(s: str) -> str:
    """Filename-safe character id. ASCII only; preserves alphanumerics and underscore."""
    s = str(s)
    s = s.replace("::", "__")
    # Best-effort ASCII fold: drop diacritics
    import unicodedata
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.replace("ſ", "s")
    s = re.sub(r"[^\w\-]", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "untitled"


def truncate(s: str, n: int) -> str:
    if not isinstance(s, str):
        return ""
    s = re.sub(r"\s+", " ", s).strip()
    if len(s) <= n:
        return s
    return s[:n].rsplit(" ", 1)[0] + "…"


def sort_decades(values):
    known, unknown = [], []
    for v in values:
        (unknown if str(v).lower() == "unknown" else known).append(v)
    known.sort(key=lambda v: int(str(v).rstrip("s")) if str(v).rstrip("s").isdigit() else 10**9)
    return known + unknown


# -------------------------------------------------------------------
# Important-excerpt extraction
# -------------------------------------------------------------------
def _parse_top_words(s) -> list[str]:
    if not isinstance(s, str):
        return []
    return [w.strip() for w in s.split(",") if w.strip()]


def find_excerpts(speech: str, keywords: list[str], n: int) -> list[tuple[str, list[str]]]:
    """Extract up to n passages from `speech` that contain the most cluster keywords.

    Returns list of (passage, matched_keywords_in_passage). Each passage is a
    window of ~2*EXCERPT_HALF_WINDOW characters around a keyword hit, snapped
    to word boundaries and de-duplicated against earlier picks.
    """
    if not isinstance(speech, str) or not speech.strip() or not keywords:
        return []
    speech_lower = speech.lower()
    picks = []   # list of (start_idx, passage, matched_keywords)

    # For each keyword in priority order, find its first not-yet-covered occurrence
    for kw in keywords:
        kw_lc = kw.lower()
        if len(kw_lc) < 3:
            continue
        start = 0
        while True:
            idx = speech_lower.find(kw_lc, start)
            if idx == -1:
                break
            # Is this position inside an already-chosen window?
            if any(abs(idx - p[0]) < EXCERPT_HALF_WINDOW for p in picks):
                start = idx + len(kw_lc)
                continue
            # Build window, snap to word boundaries
            lo = max(0, idx - EXCERPT_HALF_WINDOW)
            hi = min(len(speech), idx + len(kw_lc) + EXCERPT_HALF_WINDOW)
            while lo > 0 and not speech[lo - 1].isspace():
                lo -= 1
            while hi < len(speech) and not speech[hi].isspace():
                hi += 1
            passage = speech[lo:hi].strip()
            # Collect ALL cluster keywords that appear in this passage
            passage_lc = passage.lower()
            hits = [k for k in keywords if k.lower() in passage_lc and len(k) >= 3]
            picks.append((idx, passage, hits))
            if len(picks) >= n:
                break
            start = idx + len(kw_lc)
        if len(picks) >= n:
            break

    # Re-rank picks by number of distinct keywords matched (then by appearance order)
    picks.sort(key=lambda t: (-len(set(t[2])), t[0]))
    return [(p, h) for _, p, h in picks[:n]]


def highlight_keywords(text: str, keywords: list[str]) -> str:
    """HTML-escape `text` and wrap occurrences of `keywords` in <mark>."""
    if not text:
        return ""
    escaped = esc(text)
    # Build a pattern that matches any keyword as a whole word, case-insensitive
    if not keywords:
        return escaped
    pat = re.compile(
        r"\b(" + "|".join(re.escape(k) for k in sorted(set(keywords), key=len, reverse=True)) + r")\b",
        re.IGNORECASE,
    )
    return pat.sub(lambda m: f"<mark>{m.group(0)}</mark>", escaped)


# -------------------------------------------------------------------
# Renderers
# -------------------------------------------------------------------
def cluster_label_for(cluster_id: int, df: pd.DataFrame) -> str:
    sub = df[df.cluster == cluster_id]
    if "topic_label" in sub.columns and sub["topic_label"].notna().any():
        return str(sub["topic_label"].iloc[0])
    return f"Cluster {cluster_id}"


def render_meta_line(row: pd.Series) -> str:
    """One-liner with author / date / genre / company / theater.
    Uses the performance-first roster year when present (Entry 007) so the
    cluster page is internally consistent; falls back to the display year."""
    parts = []
    if isinstance(row.get("author"), str) and row["author"].strip():
        parts.append(esc(row["author"]))
    _y = row.get("year_roster") if pd.notna(row.get("year_roster")) else row.get("year")
    if pd.notna(_y):
        parts.append(str(int(_y)))
    if isinstance(row.get("genre"), str) and row["genre"].strip():
        parts.append(esc(row["genre"]))
    if isinstance(row.get("company"), str) and row["company"].strip():
        parts.append(esc(row["company"]))
    if isinstance(row.get("theater"), str) and row["theater"].strip():
        parts.append(esc(row["theater"]))
    return " · ".join(parts)


def render_decade_bars(decade_counts: dict) -> str:
    if not decade_counts:
        return "<p><em>No dated plays in this cluster.</em></p>"
    max_n = max(decade_counts.values())
    rows = []
    for d in sort_decades(list(decade_counts.keys())):
        n = decade_counts[d]
        w = max(1, int(round(220 * n / max_n)))
        rows.append(
            f'<div class="bar"><div class="label">{esc(d)}</div>'
            f'<div class="fill" style="width:{w}px"></div>'
            f'<div class="count">{n}</div></div>'
        )
    return "\n".join(rows)


def render_author_tags(author_counts: pd.Series, limit: int = 18) -> str:
    tags = []
    for au, n in author_counts.head(limit).items():
        label = au if (isinstance(au, str) and au.strip()) else "(unknown)"
        tags.append(f'<span class="tag">{esc(label)}<span class="n">{n}</span></span>')
    if len(author_counts) > limit:
        tags.append(f'<span class="tag">+{len(author_counts) - limit} more</span>')
    return "\n".join(tags)


def render_character_block_for_cluster_page(row: pd.Series, keywords: list[str],
                                            why: list[str] | None = None) -> str:
    """Block rendered inside a cluster page: header + 2 excerpts + 'full' link.
    `why` = which landmark set(s) selected this member (typical/early/familiar),
    rendered as chips so the excerpt section explains its own sampling (item 1.6a)."""
    char_id = row.get("character_id", "")
    slug = slugify(char_id)
    display = row.get("display_name") or row.get("normalized_name") or "?"
    raw = row.get("raw_names", "")
    play = row.get("title", "")
    meta = render_meta_line(row)
    role = row.get("role_description", "")
    n_words = "" if pd.isna(row.get("n_words")) else int(row["n_words"])

    excerpts = find_excerpts(row.get("speech_text", "") or "",
                             keywords, N_EXCERPTS_PER_CHAR_CLUSTER_PAGE)
    if excerpts:
        ex_html = "\n".join(
            f'<div class="excerpt">{highlight_keywords(p, hits)}</div>'
            for p, hits in excerpts
        )
    else:
        ex_html = ('<div class="excerpt"><em>No keyword-matching excerpt found; '
                   'see the full speech on the character page.</em></div>')

    chips = "".join(f'<span class="chip chip-{esc(w)}">{esc(w)}</span>' for w in (why or []))
    return f"""
<div class="character-block">
  <div class="ch-head">
    <div class="name"><a href="characters/{slug}.html">{esc(display)}</a>
      <span class="muted"> in <em>{esc(play)}</em></span>{chips}
    </div>
    <div class="meta">{meta}<br>{n_words} words</div>
  </div>
  {f'<div class="muted" style="color:var(--muted); font-size:.9rem; margin-top:.2em">Role: {esc(truncate(role, 240))}</div>' if isinstance(role, str) and role.strip() else ''}
  {ex_html}
  <div style="font-size:.88rem; margin-top:.4em">
    <a href="characters/{slug}.html">→ View full speech and metadata</a>
    {f'<span class="muted" style="color:var(--muted)"> · speech prefix(es): {esc(raw)}</span>' if isinstance(raw, str) and raw and raw != display else ''}
  </div>
</div>
"""


def _first_author(r) -> str:
    from utils import split_facets
    f = split_facets(r.get("author"))
    return f[0].split(",")[0].strip() if f else ""


def facet_counts(series: pd.Series, unknown_label: str | None = None,
                 kind: str | None = None) -> pd.Series:
    """Value counts over ATOMIC facets of a ';'-joined multi-valued column
    ("Tragedy; History" counts once for Tragedy AND once for History)."""
    from collections import Counter
    from utils import split_facets
    c: Counter = Counter()
    n_unknown = 0
    for v in series:
        f = split_facets(v, kind=kind)
        if not f:
            n_unknown += 1
        c.update(f)
    out = pd.Series(c).sort_values(ascending=False)
    if unknown_label and n_unknown:
        out[unknown_label] = n_unknown
        out = out.sort_values(ascending=False)
    return out


def render_cluster_page(cluster_id: int, df: pd.DataFrame, labels: pd.DataFrame,
                        meta: dict, ctx: dict, summary: dict) -> str:
    # Chronological order: the genealogical reading — earliest members first,
    # successors after suit. PERFORMANCE-FIRST dating (Entry 007): sort and
    # Year column use year_roster (first-performance year where parseable,
    # else catalogued year, else the Entry-005 display fill year).
    sub = (df[df.cluster == cluster_id].copy()
           .sort_values(["year_roster", "n_words"], ascending=[True, False], na_position="last")
           .reset_index(drop=True))
    n = len(sub)
    label = cluster_label_for(cluster_id, df)
    meta_entry = meta.get(cluster_id, {})
    top_words_str = labels.loc[cluster_id, "top_words"] if cluster_id in labels.index else ""
    # Excerpt extraction always uses the algorithmic c-TF-IDF words (they are
    # what the highlighting explains); curated display_keywords only change
    # what the lede SHOWS (item 1.6c).
    keywords = _parse_top_words(top_words_str)
    if "centroid_sim" not in sub.columns:
        sub["centroid_sim"] = float("nan")

    author_counts = facet_counts(sub["author"], unknown_label="(unknown)", kind="author")
    decade_counts = (decade_series(sub["year_roster"]).fillna("Unknown")
                     .astype(str).value_counts().to_dict())
    genre_counts = facet_counts(sub["genre"])
    years = sub["year_roster"].dropna()
    yr_str = f"{int(years.min())}–{int(years.max())} (median {int(years.median())})" if len(years) else "undated"

    title = f"Cluster {cluster_id} — {label.split(': ', 1)[-1]}"

    # ---- Emergence + prototype candidates (Entry 007) -----------------
    emg = compute_emergence(sub)
    proto_set = set(emg.get("proto_idx", []))
    formative_set = emg.get("formative_idx", set())

    # ---- Landmarks: prototypes + most typical + most familiar ---------
    proto_lm = sub.loc[emg["proto_idx"]] if emg else sub.iloc[0:0]
    typical = (sub[~sub.index.isin(proto_lm.index)]
               .nlargest(min(6, n), "centroid_sim"))
    fam_mask = sub["author"].astype(str).apply(
        lambda a: any(f in a for f in FAMILIAR_AUTHORS))
    familiar = (sub[fam_mask & ~sub.index.isin(typical.index)
                    & ~sub.index.isin(proto_lm.index)]
                .nlargest(4, "n_words"))

    def lm_card(r, tag, badge_cls="badge"):
        slug = slugify(r.get("character_id", ""))
        sim = "" if pd.isna(r.get("centroid_sim")) else f" · typicality {r['centroid_sim']:.2f}"
        _y = r.get("year_roster")
        yr = "" if pd.isna(_y) else f", {int(_y)}"
        return (f'<div class="lm-card"><div class="who">'
                f'<a href="characters/{slug}.html">{esc(r.get("display_name") or "?")}</a>'
                f'<span class="{badge_cls}">{tag}</span></div>'
                f'<div class="whence">{esc(truncate(str(r.get("title") or ""), 60))}'
                f'{yr} · {esc(_first_author(r))}{sim}</div></div>')

    landmarks_html = "".join(
        [lm_card(r, "prototype", "badge badge-proto") for _, r in proto_lm.iterrows()] +
        [lm_card(r, "typical", "badge chip-typical") for _, r in typical.iterrows()] +
        [lm_card(r, "familiar") for _, r in familiar.iterrows()])

    # ---- Full chronological roster ------------------------------------
    proto_title = (f"formative era (≤{emg['established']}) · typicality ≥ cluster "
                   f"median {emg['gate']:.2f}") if emg else ""
    table_rows = []
    for i, r in sub.iterrows():
        slug = slugify(r.get("character_id", ""))
        nm = esc(r.get("display_name") or "?")
        badge = (f'<span class="badge badge-proto" title="{esc(proto_title)}">prototype</span>'
                 if i in proto_set else "")
        row_cls = ' class="formative"' if i in formative_set else ""
        play = esc(truncate(str(r.get("title") or ""), 60))
        au = esc(_first_author(r))
        yr = "" if pd.isna(r.get("year_roster")) else int(r["year_roster"])
        gn = esc(r.get("genre", ""))
        nw = "" if pd.isna(r.get("n_words")) else int(r["n_words"])
        sim = "" if pd.isna(r.get("centroid_sim")) else f"{r['centroid_sim']:.2f}"
        table_rows.append(
            f"<tr{row_cls}><td><a href='characters/{slug}.html'>{nm}</a>{badge}</td>"
            f"<td>{play}</td><td>{au}</td><td class='num' data-v='{yr if yr != '' else 9999}'>{yr}</td>"
            f"<td>{gn}</td><td class='num'>{nw}</td>"
            f"<td class='num' data-v='{sim if sim else -1}'>{sim}</td></tr>"
        )
    table_html = (
        "<table class='sortable'><thead><tr>"
        "<th>Character</th><th>Play</th><th>Author</th><th>Year</th>"
        "<th>Genre</th><th>Words</th><th>Typicality</th>"
        "</tr></thead><tbody>"
        + "".join(table_rows) + "</tbody></table>"
    )

    # ---- Representative excerpts: prototypes ∪ typical ∪ familiar ------
    rep_ids = list(dict.fromkeys(          # preserve order, drop dupes
        list(proto_lm.index) + list(typical.index) + list(familiar.index)))[:12]
    # why-chips: which landmark set(s) put each member here (item 1.6a)
    rep_why: dict[int, list[str]] = {}
    for i in proto_lm.index:
        rep_why.setdefault(i, []).append("prototype")
    for i in typical.index:
        rep_why.setdefault(i, []).append("typical")
    for i in familiar.index:
        rep_why.setdefault(i, []).append("familiar")
    rep = sub.loc[rep_ids].sort_values("year_roster", na_position="last")
    excerpt_blocks = "\n".join(
        render_character_block_for_cluster_page(r, keywords, rep_why.get(i, []))
        for i, r in rep.iterrows()
    )

    # ---- Plot summaries (collapsed) ------------------------------------
    plays = sub.drop_duplicates("TCP").sort_values("year_roster", na_position="last")
    plot_blocks = []
    for _, r in plays.iterrows():
        plot = truncate(r.get("plot", "") or "", 1500)
        if not plot:
            continue
        meta = render_meta_line(r)
        plot_blocks.append(
            f'<div class="plot"><div class="title">{esc(r.get("title", ""))}</div>'
            f'<div class="meta">{meta}</div>'
            f'<div class="body">{esc(plot)}</div></div>'
        )
    plot_html = "\n".join(plot_blocks) if plot_blocks else "<p><em>No plot summaries available.</em></p>"

    gtop = " · ".join(f"{esc(k)} {v / n:.0%}" for k, v in genre_counts.head(3).items())

    # ---- Tier-1 sections (2026-07-10): banner, vocabulary lede, curated
    # block, historical profile, signatures --------------------------------
    banner = render_reading_banner(summary)
    name_badge = ""   # proposed-name badges removed (Entry 010)
    curated_block = render_curated_block(meta_entry)

    disp_kw = meta_entry.get("display_keywords") or ""
    if isinstance(disp_kw, list):
        disp_kw = ", ".join(disp_kw)
    if disp_kw.strip():
        vocab_lede = (f'<p class="lede">Register keywords (curated): <em>{esc(disp_kw)}</em></p>')
        algo_vocab_details = (f"<h3>Algorithmic distinguishing vocabulary (c-TF-IDF)</h3>"
                              f"<p><em>{esc(top_words_str)}</em> — these drive the excerpt "
                              f"highlighting below.</p>")
        kw_caveat = ""
    else:
        vocab_lede = f'<p class="lede">Distinguishing vocabulary: <em>{esc(top_words_str)}</em></p>'
        algo_vocab_details = ""
        kw_caveat = ('<p class="kw-caveat">Tokens that look like proper names in this list '
                     '(e.g. <code>massinissa</code>, <code>faukenbridge</code>) are residue of '
                     'incomplete name-masking, not register — a second masking pass is pending '
                     '(PROVENANCE_LOG §7.3).</p>')

    temporal_html, time_badges = render_temporal_strip(sub, ctx)
    time_badge_html = "".join(f'<span class="badge badge-time">{esc(b)}</span>' for b in time_badges)
    signature_html = render_signature_panel(sub, ctx)

    # ---- Fact strip under the title (Entry 008) -------------------------
    yr_rng = f"{int(years.min())}–{int(years.max())}" if len(years) else "undated"
    yr_med = f"median {int(years.median())} · perf-first" if len(years) else ""
    facts = [
        (f"{n}", "characters"),
        (f"{sub['TCP'].nunique()}", "plays"),
        (f"{len(author_counts)}", "authors"),
        (yr_rng, yr_med or "years"),
    ]
    if emg:
        facts.append((f"est. {emg['established']}", "type established"))
    facts_html = ('<div class="facts">'
                  + "".join(f'<div class="f"><b>{esc(v)}</b><i>{esc(l)}</i></div>'
                            for v, l in facts)
                  + '</div>')
    genre_line = (f'<div class="kvp" style="margin-top:-.6em">{gtop}</div>' if gtop else "")

    # ---- Ledes for landmarks / roster (Entry 007 wording) ---------------
    landmarks_lede = (
        '<p class="lede" style="font-size:.92rem">'
        + ('The candidate <b>prototypes</b> (formative-era members with above-median '
           'typicality — see the roster below), ' if emg else '')
        + 'the most <b>typical</b> members (closest to the cluster centroid) and the most '
          '<b>familiar</b> ones (major-author roles). Typicality is cosine similarity to the '
          'cluster centre — low values mean a blended, atypical member.</p>')

    if emg:
        roster_lede = (
            f'<p class="lede" style="font-size:.92rem">A genealogical reading under '
            f'<b>performance-first dating</b>: first-performance year where known '
            f'({emg["n_perf"]} of {emg["n_dated"]} dated members), else the catalogued year — '
            f'so years here can sit earlier than in the historical profile above, which keeps '
            f'the published print-year basis. First recorded <b>{emg["first_year"]}</b> '
            f'({esc(emg["first_name"])}, <em>{esc(truncate(emg["first_play"], 60))}</em>); '
            f'established by <b>{emg["established"]}</b> — the year the first tenth of the '
            f'cluster\'s dated members had appeared. Tinted rows fall in that formative era; '
            f'<span class="badge badge-proto">prototype</span> marks its most typical members '
            f'(typicality ≥ cluster median {emg["gate"]:.2f}; top {min(PROTO_TOP_N, emg["n_pass_gate"])} '
            f'of {emg["n_pass_gate"]} qualifying of {emg["n_formative"]} formative) — the strongest '
            f'candidates for this voice\'s founding exemplars. Early members below the gate are '
            f'more likely blends than models; kinship, not proven indebtedness. Click a column '
            f'header to re-sort. Full rules: <a href="methods.html">Methods &amp; labels</a>.</p>')
    else:
        roster_lede = (
            '<p class="lede" style="font-size:.92rem">Chronological roster under '
            'performance-first dating (first-performance year where known, else the catalogued '
            f'year). Fewer than {EMERGE_MIN_DATED} members are dated, so no emergence estimate '
            'or prototype badges are shown. Click a column header to re-sort. '
            'Full rules: <a href="methods.html">Methods &amp; labels</a>.</p>')

    return f"""<!doctype html>
<html lang="en"><head>
{page_head(title)}
</head><body>
{masthead("", "clusters")}
<div class="wrap">

<nav class="crumbs">
  <a href="index.html">Home</a> ›
  <a href="cluster_evidence.html">All clusters</a> ›
  <span>Cluster {cluster_id}</span>
</nav>

<h1>{esc(title)}{name_badge}</h1>
{vocab_lede}
{kw_caveat}
{facts_html}
{genre_line}
{banner}

{curated_block}

<h2>Historical profile {time_badge_html}</h2>
{temporal_html}

<h2>Signatures</h2>
{signature_html}

<h2>Landmarks</h2>
{landmarks_lede}
<div class="landmarks">{landmarks_html}</div>

<h2>All {n} characters, oldest first</h2>
{roster_lede}
{table_html}

<h2>Representative speech excerpts</h2>
<p class="lede" style="font-size:.92rem">Shown for the prototype, typical, and familiar
members above — passages containing the cluster's distinguishing words (highlighted).</p>
{excerpt_blocks}

<details><summary>Full authorship list &amp; decade counts</summary>
<h3>Authorship (raw counts)</h3>
{render_author_tags(author_counts)}
<h3>Decade distribution (raw counts, performance-first dating)</h3>
{render_decade_bars(decade_counts)}
{algo_vocab_details}
</details>

<details><summary>Plot summaries for the {sub['TCP'].nunique()} plays represented</summary>
{plot_html}
</details>

<div class="footer">
  Generated automatically from <code>cluster_xy_table__{config.CLUSTER_TABLES[0]}.csv</code> by
  <code>code/07_generate_site.py</code>. How the labels are computed:
  <a href="methods.html">Methods &amp; labels</a>. View the
  <a href="https://github.com/hkim1596/early-modern-drama-character-clustering">source on GitHub</a>.
</div>
</div>{SORT_JS}</body></html>"""


def render_character_page(row: pd.Series, df: pd.DataFrame, labels: pd.DataFrame) -> str:
    """Per-character deep-dive page: full speech + all metadata + excerpts."""
    cluster_id = int(row["cluster"]) if pd.notna(row["cluster"]) else -1
    label = cluster_label_for(cluster_id, df) if cluster_id != -1 else "Outlier"
    label = label.split(": ", 1)[-1]   # strip any "NN: " prefix from topic_label
    top_words_str = labels.loc[cluster_id, "top_words"] if cluster_id in labels.index else ""
    keywords = _parse_top_words(top_words_str)
    speech = row.get("speech_text", "") or ""

    display = row.get("display_name") or row.get("normalized_name") or "?"
    play    = row.get("title", "")
    author  = row.get("author", "")
    year    = "" if pd.isna(row.get("year")) else int(row["year"])
    decade  = row.get("Date_Decade", "")
    genre   = row.get("genre", "")
    play_t  = row.get("play_type", "")
    company = row.get("company", "")
    theater = row.get("theater", "")
    role    = row.get("role_description", "")
    raw     = row.get("raw_names", "")
    n_words = "" if pd.isna(row.get("n_words")) else int(row["n_words"])
    n_chars = "" if pd.isna(row.get("n_chars")) else int(row["n_chars"])

    # First-performance year (Entry 007 dating; shown alongside the
    # catalogued year since the Entry-008 full regeneration)
    perf = "" if pd.isna(row.get("year_perf")) else int(row["year_perf"])

    # Metadata table — every available field
    meta_rows = []
    for label_text, val in [
        ("Play",            play),
        ("Author",          author),
        ("Year (catalogued)", year),
        ("First performance", perf),
        ("Decade",          decade),
        ("Genre",           genre),
        ("Play type",       play_t),
        ("Company",         company),
        ("Theater",         theater),
        ("Role description", role),
        ("Speech prefix(es)", raw),
        ("Words",           n_words),
        ("Characters",      n_chars),
        ("Typicality",      "" if pd.isna(row.get("centroid_sim"))
                            else f"{row['centroid_sim']:.2f} (cosine to cluster centroid)"),
        ("TCP id",          row.get("TCP", "")),
        ("BritDrama no.",   "" if pd.isna(row.get("brit_drama_number")) else row.get("brit_drama_number")),
        ("Cluster",         f"Cluster {cluster_id} — {label}" if cluster_id != -1 else "Outlier (no cluster)"),
    ]:
        if val is None or (isinstance(val, float) and pd.isna(val)):
            continue
        sval = str(val).strip()
        if not sval or sval.lower() == "nan":
            continue
        meta_rows.append(f"<tr><th>{esc(label_text)}</th><td>{esc(val)}</td></tr>")
    meta_html = "<table>" + "\n".join(meta_rows) + "</table>"

    # Important excerpts
    excerpts = find_excerpts(speech, keywords, N_EXCERPTS_PER_CHAR_DETAIL)
    if excerpts and cluster_id != -1:
        ex_intro = (f"Passages from this character's speech that contain the most "
                    f"distinguishing words for Cluster {cluster_id} "
                    f"(<em>{esc(', '.join(keywords[:6]))}…</em>). Matches are highlighted.")
        ex_html = "\n".join(
            f'<div class="excerpt">{highlight_keywords(p, hits)}</div>'
            for p, hits in excerpts
        )
    else:
        ex_intro = ("No keyword-matching excerpt could be extracted (the cluster label "
                    "doesn't share vocabulary with this character's speech).")
        ex_html = ""

    # Full speech with light formatting (just line breaks)
    full_speech_html = esc(speech) if speech else "<em>No speech text available.</em>"

    # Plot summary
    plot = truncate(row.get("plot", "") or "", 2500)
    plot_html = f'<div class="plot"><div class="title">Plot — {esc(play)}</div><div class="body">{esc(plot)}</div></div>' if plot else ""

    cluster_link = (f'<a href="cluster_{cluster_id:02d}.html">Cluster {cluster_id} — {esc(label)}</a>'
                    if cluster_id != -1 else "<em>outlier (no cluster)</em>")

    title = f"{display} in {play}"
    return f"""<!doctype html>
<html lang="en"><head>
{page_head(title, root="../")}
</head><body>
{masthead(root="../")}
<div class="wrap">

<nav class="crumbs">
  <a href="../index.html">Home</a> ›
  <a href="../cluster_evidence.html">All clusters</a> ›
  {cluster_link} ›
  <span>{esc(display)}</span>
</nav>

<h1>{esc(display)}</h1>
<p class="lede">in <em>{esc(play)}</em>{(' — ' + esc(author)) if isinstance(author, str) and author.strip() else ''}</p>

<h2>Metadata</h2>
{meta_html}

<h2>Important excerpts</h2>
<p class="lede" style="font-size:.92rem; margin-top:-.5em">{ex_intro}</p>
{ex_html}

<h2>Full speech</h2>
<div class="full-speech">{full_speech_html}</div>

{('<h2>Plot summary</h2>' + plot_html) if plot_html else ''}

<div class="footer">
  Generated automatically from <code>cluster_xy_table__{config.CLUSTER_TABLES[0]}.csv</code>.
  View other characters in this group on the
  {cluster_link} page.
</div>
</div></body></html>"""


def render_master_index(df: pd.DataFrame, labels: pd.DataFrame,
                        ctx: dict, summary: dict) -> str:
    meta = load_cluster_meta()
    top = load_cluster_meta_top()
    family_desc = top.get("families", {}) if isinstance(top.get("families"), dict) else {}
    family_order = list(dict.fromkeys(
        [meta[c].get("family", "Other") for c in sorted(meta)] + ["Other"]))
    by_family: dict[str, list[str]] = {f: [] for f in family_order}

    for cid in sorted(c for c in df.cluster.unique() if c != -1):
        sub = df[df.cluster == cid]
        n = len(sub)
        top_words = labels.loc[cid, "top_words"] if cid in labels.index else ""
        entry = meta.get(cid, {})
        name = entry.get("name", "")
        headline = f"Cluster {cid} — {esc(name)}" if name \
            else f"Cluster {cid} — {esc(cluster_label_for(cid, df))}"
        years = sub["year_roster"].dropna() if "year_roster" in sub.columns else sub["year"].dropna()
        yr_str = f"{int(years.min())}–{int(years.max())}" if len(years) else ""
        med_str = f" · median {int(years.median())}" if len(years) else ""
        emg_ix = compute_emergence(sub)
        est_str = f" · est. by {emg_ix['established']}" if emg_ix else ""
        spark = render_decade_spark(sub)

        # Three exemplar members: familiar-author roles first, then most typical
        s = sub.copy()
        s["_fam"] = s["author"].astype(str).apply(
            lambda a: any(f in a for f in FAMILIAR_AUTHORS))
        s = s.sort_values(["_fam", "centroid_sim"], ascending=[False, False]) \
            if "centroid_sim" in s.columns else s
        ex = []
        for _, r in s.head(3).iterrows():
            _y = r.get("year_roster") if pd.notna(r.get("year_roster")) else r.get("year")
            yr = "" if pd.isna(_y) else f" {int(_y)}"
            ex.append(f"{esc(r.get('display_name') or '?')} "
                      f"<span style='color:var(--muted)'>({esc(truncate(str(r.get('title') or ''), 34))},{yr})</span>")
        card = f"""
<a class="idx-card" href="cluster_{cid:02d}.html">
  <h3>{headline}</h3>
  <p>{' · '.join(ex)}<br>
     {n} characters · {sub['TCP'].nunique()} plays · {yr_str}{med_str}{est_str}{spark}<br>
     <small>{esc(top_words)}</small></p>
</a>"""
        fam = entry.get("family", "Other")
        by_family.setdefault(fam, []).append(card)

    sections = []
    for fam in family_order:
        if by_family.get(fam):
            desc = family_desc.get(fam, "")
            desc_html = f"<p class='fam-desc'>{esc(desc)}</p>" if desc else ""
            sections.append(f"<h2 class='fam'>{esc(fam)}</h2>" + desc_html
                            + "".join(by_family[fam]))

    # Historical type coverage (item 1.5): only rendered once curated —
    # top-level "attested_types" list vs per-cluster "historical_types".
    coverage_html = ""
    attested = top.get("attested_types") or []
    if attested:
        mapped: dict[str, list[int]] = {}
        for cid, entry in meta.items():
            for t in entry.get("historical_types") or []:
                mapped.setdefault(t.lower(), []).append(cid)
        rows = []
        misses = []
        for t in attested:
            cids = sorted(mapped.get(str(t).lower(), []))
            if cids:
                links = ", ".join(f'<a href="cluster_{c:02d}.html">cl{c}</a>' for c in cids)
                rows.append(f"<tr><td>{esc(t)}</td><td>{links}</td></tr>")
            else:
                misses.append(esc(str(t)))
        miss_html = (f"<p class='lede' style='font-size:.9rem'>Attested types with <b>no "
                     f"corresponding cluster</b> (the misses are evidence too): "
                     f"{', '.join(misses)}.</p>") if misses else ""
        coverage_html = (f"<h2 class='fam'>Historical type coverage</h2>"
                         f"<table><thead><tr><th>Attested type</th><th>Cluster(s)</th></tr>"
                         f"</thead><tbody>{''.join(rows)}</tbody></table>{miss_html}")

    banner = render_reading_banner(summary)

    return f"""<!doctype html>
<html lang="en"><head>
{page_head("All clusters")}
</head><body>
{masthead("", "clusters")}
<div class="wrap">

<nav class="crumbs"><a href="index.html">Home</a> › <span>All clusters</span></nav>
<h1>Character archetypes — all clusters</h1>
<p class="lede">{df.cluster.nunique() - 1} voice clusters over {(df.cluster >= 0).sum():,}
characters from {df.loc[df.cluster >= 0, "TCP"].nunique()} plays, grouped into families.
Each cluster page lists every member chronologically, with an emergence estimate
("established by" = the year the first tenth of dated members had appeared), prototype
candidates (formative-era members of above-median typicality), landmarks, typicality
scores, and speech evidence. Year ranges here and on the rosters use performance-first
dating (first-performance year where known, else the catalogued year); "est." is the
establishment year. Characters speaking fewer than 150 words are not clustered, and only
one edition of each play is included. Full rules: <a href="methods.html">Methods &amp;
labels</a>.</p>
{banner}
{''.join(sections)}

{coverage_html}

<div class="footer">
  Generated automatically by <code>code/07_generate_site.py</code> ·
  <a href="methods.html">Methods &amp; labels</a>.
</div>
</div></body></html>"""


def render_landing_page(df: pd.DataFrame, summary: dict) -> str:
    """docs/index.html — site landing (owned by stage 07 since Entry 008;
    previously a hand-maintained static file). Numbers are computed from the
    published table at build time; prose updated to the Entry-007 emergence/
    prototype semantics (the old 'earliest members are the candidate
    prototypes' wording is retired)."""
    cl = df[df.cluster >= 0]
    n = len(cl)
    n_plays = cl["TCP"].nunique()
    k = summary.get("k", "?")
    yrs = cl["year_roster"].dropna()
    span = f"{int(yrs.min())}–{int(yrs.max())}" if len(yrs) else "—"

    return f"""<!doctype html>
<html lang="en"><head>
{page_head("Early Modern Drama — Character Archetypes")}
</head><body>
{masthead("", "")}
<div class="wrap">

<div class="hero">
<h1>Character archetypes in early modern English drama</h1>
<p class="lede">A computational typology of dramatic voice, built from the complete
speech of every speaking character in the early modern English repertoire — {n:,}
characters from {n_plays} plays, grouped into {k} register clusters and traceable
across a century of theatre ({span}).</p>
</div>

<div class="facts">
  <div class="f"><b>{n:,}</b><i>characters</i></div>
  <div class="f"><b>{n_plays}</b><i>plays</i></div>
  <div class="f"><b>{k}</b><i>clusters</i></div>
  <div class="f"><b>{span}</b><i>years covered</i></div>
</div>

<div class="entries">
  <a class="entry" href="interactive_clusters__archetype.html">
    <h3>Interactive map</h3>
    <p>Every character as a point in archetype space. Hover for play, author, date and
    role; filter by decade, genre, author, company or theater.</p>
    <span class="go">Open the map →</span>
  </a>
  <a class="entry" href="cluster_evidence.html">
    <h3>Cluster evidence</h3>
    <p>One page per cluster: when the type emerged, its prototype candidates,
    historical profile, signatures, and every member with speech excerpts.</p>
    <span class="go">Browse the {k} clusters →</span>
  </a>
  <a class="entry" href="methods.html">
    <h3>Methods &amp; labels</h3>
    <p>How every number and badge is computed — typicality, emergence, prototypes,
    year bases, signatures — and what the pages do and do not claim.</p>
    <span class="go">Read the methods →</span>
  </a>
</div>

<h2>What the cluster pages show</h2>
<p>Each cluster page names an archetype and lays out its evidence: a historical profile
against the corpus baseline, author and genre signatures, landmark members, and a full
chronological roster under performance-first dating. An emergence line dates when the
type became an established resource ("established by" = the year the first tenth of its
dated members had appeared), and <b>prototype</b> badges mark the formative-era members
that are also strongly typical of the voice — the best candidates for its founding
exemplars. Typicality (cosine similarity to the cluster centre) shows how central any
member is; low-typicality members are blends of several registers, not misfits. Every
row links to the character's full speech, so each archetypal reading can be verified
against the raw text.</p>

<h2>How to read the map</h2>
<p>Each point is a single character; color encodes its archetype cluster. Hover for
play, author, date, genre, role, and the cluster's distinguishing words. Click a legend
entry to hide that cluster, double-click to isolate it. The dropdown menus highlight a
single decade, genre, author, play, play type, theater, or company — everything else
dims. Characters speaking fewer than 150 words are not shown (too little text for a
stable stylistic signature), and only one edition of each play is included. The 2-D
layout is a UMAP projection for display only — cluster membership comes from the full
embedding space.</p>

<h2>Data &amp; method in brief</h2>
<p>Characters were extracted from <a href="https://textcreationpartnership.org/"
target="_blank" rel="noopener">EEBO-TCP</a> drama transcriptions; play metadata is
merged from Wiggins &amp; Richardson's <em>British Drama: A Catalogue of Plays</em> and
from <a href="https://deep.sas.upenn.edu/" target="_blank" rel="noopener">DEEP</a>.
Speech is typographically normalized, spelling-modernized (MorphAdorner), and proper
nouns are masked so clusters reflect register rather than shared names. Each
character's speech is embedded with <code>{config.EMBED_MODEL.split("/")[-1]}</code> in
~{config.EMBED_CHUNK_TOKENS}-token windows, mean-pooled per character; play-level
signal is removed by leave-one-out play centering; the typology is spherical k-means
(k={k}). The space is a continuum with dense regions — read clusters as density peaks,
not boxes; the <a href="methods.html">methods page</a> spells out every rule, and every
data-affecting decision is recorded in the project's
<a href="{REPO_URL}/blob/main/PROVENANCE_LOG.md">provenance log</a>.</p>

<div class="footer">
  Heejin Kim · built with Python, transformers, scikit-learn, UMAP, and Plotly ·
  <a href="{REPO_URL}">source on GitHub</a> · <a href="methods.html">Methods &amp; labels</a>
</div>
</div></body></html>"""


def render_methods_page(df: pd.DataFrame, ctx: dict, summary: dict) -> str:
    """docs/methods.html — how every on-page label and number is computed.
    Concise one-pager (approved 2026-07-10, PROVENANCE_LOG Entry 007).
    Numbers are read from cluster_summary / the table at build time wherever
    they live in a data file; the seed-ARI text reuses SEED_ARI_TEXT."""
    cl = df[df.cluster >= 0]
    n = len(cl)
    k = summary.get("k", "?")
    seed = summary.get("random_state", "?")
    sil = summary.get("silhouette_cosine_full")
    sil_s = f"{sil:.3f}" if isinstance(sil, (int, float)) else "?"
    minw = summary.get("min_words", 150)
    n_plays = cl["TCP"].nunique()
    dated_perf = int(cl["year_perf"].notna().sum())
    dated_gen = int(cl["year_gen"].notna().sum())
    dated_disp = int(cl["year_roster"].notna().sum())
    r2_raw = summary.get("length_r2_raw")
    r2_fin = summary.get("length_r2_final")
    r2_s = (f"{r2_raw:.2f} → {r2_fin:.2f}"
            if isinstance(r2_raw, (int, float)) and isinstance(r2_fin, (int, float)) else "—")

    return f"""<!doctype html>
<html lang="en"><head>
{page_head("Methods & labels")}
</head><body>
{masthead("", "methods")}
<div class="wrap methods">

<nav class="crumbs">
  <a href="index.html">Home</a> ›
  <a href="cluster_evidence.html">All clusters</a> ›
  <span>Methods &amp; labels</span>
</nav>

<h1>Methods &amp; labels</h1>
<p class="lede">How every number and badge on these pages is computed. Partition:
{PARTITION_NOTE} (k={k}, seed {seed}, {n:,} characters from {n_plays} plays).
Added 2026-07-10; every methodological decision is recorded in the repository's
<a href="https://github.com/hkim1596/early-modern-drama-character-clustering/blob/main/PROVENANCE_LOG.md">PROVENANCE_LOG</a>.</p>

<h2>Corpus and characters</h2>
<p>The corpus is the drama subset of EEBO-TCP: {summary.get("embedding_rows", 9638):,}
speaking characters extracted from 557 playbook transcriptions, each character
represented by everything they speak. Speech prefixes were mapped to characters
play-by-play (with an LLM-assisted, fully recorded speaker-mapping pass). Two kinds of
row are excluded from clustering, not from the data: characters speaking fewer than
{minw} words (no stable stylistic signature), and duplicate editions of the same play —
one edition is kept per work, confirmed by cast overlap, with New Oxford Shakespeare
canonical choices for Shakespeare adopted under an explicit provenance note. That leaves
the {n:,} clustered characters shown here.</p>

<h2>From speeches to a character space</h2>
<p>Character and place names in the speeches are masked (<code>someone</code>,
<code>that place</code>, …) and spelling is modernized, so clusters reflect register
rather than named content. Each character's masked speech is embedded with
<code>{config.EMBED_MODEL.split("/")[-1]}</code> in {config.EMBED_CHUNK_TOKENS}-token
chunks, token-weighted mean-pooled into one vector. Two corrections then make the space
about <em>characters</em> rather than plays: leave-one-out play centering (each character
minus the mean of its play-mates — "how does this voice differ from its own play?") and
linear removal of the document-length direction (length R² {r2_s}). Spherical k-means
with k={k} (seed {seed}) partitions the result.</p>

<h2>Read clusters as regions, not boxes</h2>
<p>The space is a continuum with dense regions: silhouette {sil_s}, {SEED_ARI_TEXT}.
Clusters are density peaks in that continuum — membership is graded, boundary members
are blends, and cluster ids reshuffle on every re-run. Nothing on these pages should be
read as a hard Theophrastan pigeonhole.</p>

<h2>The labels, one by one</h2>
<p><b>Typicality.</b> Cosine similarity between a character and its cluster's centroid
in the processed space. High = close to the heart of the register; low = a blend of
several regions. It measures representativeness, never quality or importance — canonical
protagonists are often <em>low</em>-typicality blends.</p>

<p><b>Three year bases.</b> (1) <em>Catalogued year</em> — the year in the DEEP/TCP
catalogue record, largely the <em>print</em> year: used by the historical-profile strip
and its badges, matching the published report ({ctx["dated_n"]:,} dated members,
median {ctx["median"]}). (2) <em>Performance-first dating</em> — the first-performance
year where the catalogue records one ({dated_perf:,} of {dated_gen:,} dated members),
else the catalogued year: used by the roster, its Year column and sort, the emergence
line, prototype badges, index year-ranges and sparklines. Performance years run a median
of ~3 years earlier than print years, sometimes decades. (3) <em>Display fills</em> —
{dated_disp - dated_gen} characters from metadata-bare collection items carry an
approved parent-volume print year as a last-resort display date (marked in the
provenance log); these never enter the emergence computation. Character pages show the
catalogued year and, where the catalogue records one, the first-performance year.</p>

<p><b>First recorded / established by (emergence).</b> Computed per cluster on
performance-first dating, for clusters with ≥{EMERGE_MIN_DATED} dated members.
<em>First recorded</em> is the earliest dated member. <em>Established by</em> is the year
the first tenth of the cluster's dated members had appeared — the point where the type
stops being sporadic and becomes an available resource. (Fixed-count burst rules were
tested and rejected: they collapse to the corpus onset for nearly every cluster,
tracking survival of playbooks rather than the type's own take-off.)</p>

<p><b>Prototype.</b> A member of the formative era (dated up to the establishment year)
whose typicality is at or above the cluster median; the top {PROTO_TOP_N} by typicality
are badged. This replaces an earlier "early" badge that marked the five oldest dated
members regardless of typicality (on average those sat at the 35th typicality percentile
of their cluster — old, but mostly blends, and weak evidence for a prototype claim).
Prototype badges assert kinship and priority within the corpus, not proven indebtedness:
a directed temporal nearest-neighbour genealogy is planned as the real lineage
instrument.</p>

<p><b>early-rooted / late register.</b> Historical-profile badges on the catalogued-year
basis, for clusters with ≥{MIN_DATED_FOR_BADGES} dated members: <em>early-rooted</em> =
pre-1590 share ≥ {BADGE_EARLY_LIFT}× the corpus share; <em>late register</em> =
post-1625 share ≥ {BADGE_LATE_LIFT}× corpus <em>and</em> median year above the corpus
median ({ctx["median"]}).</p>

<p><b>Signatures (×lift).</b> For authors, genres, companies, theaters and play types:
the share of the cluster's members carrying the facet ÷ the same share over all
{n:,} clustered characters. Shown only for facets carried by ≥{SIG_MIN_N["genre"]}
members (authors ≥{SIG_MIN_N["author"]}) with lift ≥ {SIG_MIN_LIFT}; top {SIG_TOP}.
Multi-valued fields are split into atomic facets first.</p>

<p><b>Distinguishing vocabulary.</b> c-TF-IDF over the masked, modernized speech text,
with stoplists and a character-name blocklist. Name-like tokens that survive
(e.g. <code>mephastophilis</code>) are residue of incomplete masking, not register —
a second masking pass is a recorded open item. These words drive the excerpt
highlighting.</p>

<p><b>Cluster names and families.</b> Names are curation, not computation: all 25 are
assigned by the author (Heejin Kim) against the cluster profiles, and the drafting
provenance of each name is recorded in the names file and the provenance log
(Entries 004 and 009) rather than displayed on the pages. c-TF-IDF fallback labels
appear where no name is curated yet (e.g. after a re-clustering). Family groupings on
the index are curated the same way.</p>

<h2>What these pages do not claim</h2>
<p>Survival is not production: dating and counts describe the <em>extant, dated</em>
record. Priority is not influence: "prototype" marks the earliest typical exemplars in
the corpus, not demonstrated imitation. Membership is not essence: a low-typicality
member is evidence of blending, not misclassification. The partition is one defensible
view of a continuous space, published with its instability measured and stated.</p>

<h2>Provenance</h2>
<p>Every data-affecting change — canonical-edition choices, approved metadata fills,
year-basis decisions, label-rule changes — is logged with dates, approvals and commit
hashes in <a href="https://github.com/hkim1596/early-modern-drama-character-clustering/blob/main/PROVENANCE_LOG.md">PROVENANCE_LOG.md</a>.
The full pipeline (stages 01–07) and all derived tables are in the
<a href="https://github.com/hkim1596/early-modern-drama-character-clustering">repository</a>;
re-running stages 04–07 regenerates this site.</p>

<div class="footer">
  Generated automatically by <code>code/07_generate_site.py</code> ·
  <a href="cluster_evidence.html">All clusters</a>
</div>
</div></body></html>"""


# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------
def main() -> None:
    import argparse
    ap = argparse.ArgumentParser(description="Generate the static evidence site")
    ap.add_argument("--no-characters", action="store_true",
                    help="regenerate cluster pages + master index only; leave the "
                         "existing docs/characters/ pages untouched (they do not "
                         "depend on the cluster-page template)")
    args = ap.parse_args()

    cxy = config.DATA_DIR / f"cluster_xy_table__{config.CLUSTER_TABLES[0]}.csv"
    if not cxy.exists():
        raise FileNotFoundError(f"{cxy} not found. Run 04_cluster.py first.")
    df = pd.read_csv(cxy, low_memory=False)
    # Analysis-grade year (performance year, pre-fill) captured BEFORE
    # derive_display_columns applies the Entry-005 display fills — the
    # historical-profile strip and its badges use this; see _analysis_years.
    _yr = pd.to_numeric(df["year"], errors="coerce")
    _need = _yr.isna() & df["year"].notna()
    _yr.loc[_need] = pd.to_numeric(
        df.loc[_need, "year"].astype(str).str.extract(r"(\d{4})")[0], errors="coerce")
    from utils import derive_display_columns
    df = derive_display_columns(
        df, fills_path=config.DATA_DIR / "manual_metadata_fills.json")
    df["year_analysis"] = _yr
    df["cluster"] = df["cluster"].astype(int)

    # Performance-first dating (Entry 007). year_perf = parsed
    # date_first_performance (numeric, else first 4-digit run), sanity-bounded.
    # year_gen = perf-first ANALYSIS basis for emergence/prototypes (falls back
    # to the catalogued year; Entry-005 display fills NEVER enter it).
    # year_roster = what cluster pages display/sort by (last-resort fallback to
    # the display year, which carries the approved fills, so no row is undated).
    if "date_first_performance" in df.columns:
        _perf = pd.to_numeric(df["date_first_performance"], errors="coerce")
        _pneed = _perf.isna() & df["date_first_performance"].notna()
        _perf.loc[_pneed] = pd.to_numeric(
            df.loc[_pneed, "date_first_performance"].astype(str)
              .str.extract(r"(\d{4})")[0], errors="coerce")
        lo, hi = YEAR_SANE_RANGE
        n_bad = int(((_perf < lo) | (_perf > hi)).sum())
        if n_bad:
            print(f"   ⚠ {n_bad} parsed performance year(s) outside {lo}–{hi} treated as missing")
        _perf = _perf.where((_perf >= lo) & (_perf <= hi))
    else:
        _perf = pd.Series(float("nan"), index=df.index)
    df["year_perf"] = _perf
    df["year_gen"] = _perf.fillna(df["year_analysis"])
    df["year_roster"] = df["year_gen"].fillna(df["year"])

    lbl_path = config.DATA_DIR / f"cluster_labels__{config.CLUSTER_TABLES[0]}.csv"
    if lbl_path.exists():
        labels = pd.read_csv(lbl_path).set_index("cluster")
    else:
        labels = pd.DataFrame(columns=["top_words"]).set_index(pd.Index([], name="cluster"))

    meta = load_cluster_meta()
    summary = load_cluster_summary()
    ctx = corpus_context(df)
    print(f"📊 Corpus baselines (clustered, dated n={ctx['dated_n']}): "
          f"median {ctx['median']}, pre-1590 {ctx['pre_share']:.1%}, "
          f"post-1625 {ctx['post_share']:.1%}")

    out_dir = config.RESULTS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    chars_dir = out_dir / "characters"
    chars_dir.mkdir(parents=True, exist_ok=True)

    # 1) cluster pages (non-outlier clusters only)
    clusters = sorted(c for c in df.cluster.unique() if c != -1)
    print("📅 Emergence (performance-first): first / established by (dated n; gate passes)")
    for cid in clusters:
        e = compute_emergence(df[df.cluster == cid])
        if e:
            print(f"   cl{cid:02d}: {e['first_year']} / est. {e['established']}  "
                  f"({e['n_dated']} dated; {e['n_pass_gate']}/{e['n_formative']} "
                  f"formative pass the median-typicality gate)")
        else:
            print(f"   cl{cid:02d}: fewer than {EMERGE_MIN_DATED} dated — no emergence line")
    for cid in clusters:
        (out_dir / f"cluster_{cid:02d}.html").write_text(
            render_cluster_page(cid, df, labels, meta, ctx, summary), encoding="utf-8"
        )
    print(f"✅ {len(clusters)} cluster pages written")

    # 2) master cluster index, methods page, landing page, stylesheet
    (out_dir / "cluster_evidence.html").write_text(
        render_master_index(df, labels, ctx, summary), encoding="utf-8"
    )
    print(f"✅ cluster_evidence.html written")
    (out_dir / "methods.html").write_text(
        render_methods_page(df, ctx, summary), encoding="utf-8"
    )
    print(f"✅ methods.html written")
    (out_dir / "index.html").write_text(
        render_landing_page(df, summary), encoding="utf-8"
    )
    print(f"✅ index.html (landing) written")
    (out_dir / "site.css").write_text(SITE_CSS, encoding="utf-8")
    print(f"✅ site.css written")

    # 3) character pages (only for characters in non-outlier clusters)
    if args.no_characters:
        print("⏭  character pages skipped (--no-characters)")
    else:
        clustered = df[df.cluster != -1].copy()
        n_written = 0
        for _, row in clustered.iterrows():
            slug = slugify(row.get("character_id", ""))
            page = render_character_page(row, df, labels)
            (chars_dir / f"{slug}.html").write_text(page, encoding="utf-8")
            n_written += 1
        print(f"✅ {n_written} character pages written to {chars_dir}")

    print(f"\n📂 Site is at: {out_dir}")
    print(f"   Open {out_dir}/index.html locally, or push to GitHub Pages.")


if __name__ == "__main__":
    main()
